// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.QueryProvider.Default.Command.#ctor(System.Action{Wiesend.ORM.Manager.QueryProvider.Default.Command,System.Collections.Generic.IList{System.Object}},System.Object,System.String,System.Data.CommandType,Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.QueryProvider.Default.LDAP.LDAPGenerator`1.All(Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~Wiesend.ORM.Manager.QueryProvider.Interfaces.IBatch")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.QueryProvider.Default.SQLServer.SQLServerGenerator`1.All(System.Int32,Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~Wiesend.ORM.Manager.QueryProvider.Interfaces.IBatch")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.QueryProvider.Default.SQLServer.SQLServerGenerator`1.All(Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~Wiesend.ORM.Manager.QueryProvider.Interfaces.IBatch")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.QueryProvider.Default.SQLServer.SQLServerGenerator`1.Any(Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~Wiesend.ORM.Manager.QueryProvider.Interfaces.IBatch")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Schema.Default.Database.SQLServer.SQLServerSchemaGenerator.SetupDeleteTrigger(Wiesend.ORM.Manager.Schema.Interfaces.ITable)")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Schema.Default.Database.SQLServer.SQLServerSchemaGenerator.SetupInsertUpdateTrigger(Wiesend.ORM.Manager.Schema.Interfaces.ITable)")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Session.All``1(Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Session.Any``1(Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~``0")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Session.PageCount``1(System.Int32,Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~System.Int32")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "member", Target = "~M:Wiesend.ORM.Manager.Session.Paged``1(System.Int32,System.Int32,System.String,Wiesend.ORM.Manager.QueryProvider.Interfaces.IParameter[])~System.Collections.Generic.IEnumerable{``0}")]
